backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: Upload “{{path}}”
    deleteMedia: Delete “{{path}}”
    openAuthoring: '{{message}}'

publish_mode: editorial_workflow
media_folder: "source/images/uploads"
# public_folder: "images/uploads"
relative_path: true

site_url: https://shop.mixhub.my.id/
display_url: https://shop.mixhub.my.id/

logo:
  src: https://shop.mixhub.my.id/images/logo.png
  show_in_header: true

# This also works, but it's deprecated. Same as logo.src
logo_url: https://shop.mixhub.my.id/images/logo.png

locale: 'zh-Hant'

collections :
  - name: "blog"
    label: "Blog"
    folder: "source/_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "標題", name: "title", widget: "string" }
      - { label: "發佈日期", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss", dateFormat: "YYYY-MM-DD", timeFormat: "HH:mm:ss" }
      - { label: "更新日期", name: "updated", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss", dateFormat: "YYYY-MM-DD", timeFormat: "HH:mm:ss", required: false }
      - { label: "標籤", name: "tags", widget: "list", required: false }
      - { label: "封面圖", name: "thumbnail", widget: "image", required: false }
      - { label: "描述", name: "description", widget: "text", required: false }
      - { label: "內文", name: "body", widget: "markdown", required: false }
